/* hello_signal.c */
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>

/*
SigName Number	Description
SIGABRT	6	Abnormal termination, often caused by calling the abort() function.
SIGFPE	8	A floating-point exception (erroneous arithmetic operation), such as division by zero.
SIGILL	4	Illegal instruction, which can occur due to corrupted code or an invalid function image.
SIGINT	2	Interactive attention signal, typically generated by the user pressing Ctrl+C.
SIGSEGV	11	A segmentation violation, caused by an invalid memory access.
SIGTERM	15	A termination request, the default signal sent by the kill command.
SIGHUP	1	Hangup, often sent to a process when the controlling terminal is closed.
SIGQUIT	3	Quit, generated by pressing Ctrl+\ and produces a core dump.
SIGTRAP	5	A trap for debugging, indicating a breakpoint.
SIGKILL	9	A process kill signal that cannot be caught, ignored, or blocked.
SIGUSR1	10	A user-defined signal for application-specific use.
SIGUSR2	12	A second user-defined signal.
SIGPIPE	13	A write to a pipe or socket with no reader.
SIGALRM	14	A real-timer alarm clock signal.
SIGCHLD	17	Indicates that a child process has stopped or terminated.
SIGCONT	18	Continues a process that has been stopped.
SIGSTOP	19	Stops a process (cannot be caught or ignored), often from Ctrl+Z.
SIGTSTP	20	Stop, generated from a terminal by pressing Ctrl+Z.
SIGTTIN	21	A background process attempted to read from the terminal.
SIGTTOU	22	A background process attempted to write to the terminal.
SIGWINCH	28	Notifies a process of a window size change.
SIGIO	29	I/O is now possible on a file descriptor.
SIGSYS	31	Bad system call.
*/

void handler(int signum)
{ //signal handler
  printf("I just caught Signal %d\n", signum);
  //exit(1);
	if(signum == SIGKILL)
      exit(1); //exit after printing
}

int main(int argc, char * argv[])
{
	signal(SIGALRM,handler);
	signal(SIGTERM,handler);
	signal(SIGABRT,handler);
	signal(SIGFPE,handler);
	signal(SIGILL,handler);
	signal(SIGINT,handler);
  signal(SIGSEGV,handler);

	signal(SIGHUP,handler);
	signal(SIGQUIT,handler);
	signal(SIGTRAP,handler);
	signal(SIGKILL,handler);
	signal(SIGUSR1,handler);
	signal(SIGUSR2,handler);
  signal(SIGPIPE,handler);
  signal(SIGCHLD,handler); 
	
	signal(SIGCONT,handler);
	signal(SIGSTOP,handler);
	//signal(SIGTSTP,handler);
  signal(SIGTTIN,handler);
  signal(SIGTTOU,handler);
	signal(SIGWINCH,handler);
	signal(SIGIO,handler);
	signal(SIGSYS,handler);

  while(1) {
	  sleep(10); //busy wait for signal to be delivered
	  printf("Im just looping forever waiting to catch signals\n");
	}
}